[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/login/*"
  to = "/.netlify/functions/login/:splat"
  status = 200

[[redirects]]
  from = "/deg/*"
  to = "/.netlify/functions/deg/:splat"
  status = 200
